const emojis = {
  document: '🗎',
  emptyDocument: '🗋',
  documentWithText: '🖹',
  documentWithPicture: '🖻',
  documentWithPictureAndText: '🖺',
  pageFacingUp: '📄',
  pageWithCurl: '📃',
  printer: '🖨️',
  fileFolder: '📁',
  openFileFolder: '📂',
  folder: '🗀',
  openFolder: '🗁',
  blackFolder: '🖿',
  cardIndexDividers: '🗂️',
};
